from __future__ import annotations

PRESERVATIVE_NAMES: set[str] = {
    "PHENOXYETHANOL", "SODIUM BENZOATE", "POTASSIUM SORBATE",
    "BENZYL ALCOHOL", "ETHYLHEXYLGLYCERIN", "CAPRYLYL GLYCOL",
    "METHYLPARABEN", "PROPYLPARABEN", "SORBIC ACID",
    "DEHYDROACETIC ACID", "CHLORPHENESIN",
}
